---
- name: Installing necessary packages.
  hosts: node2
  tasks:
  - name: Installing epel repositories.  
    command: yum install epel-release -y

# ASSUMPTION -: tarball of source_code is already present on node server.


  - name: Installing epel*, git, nodejs, npm.
    yum:
        name:  git, nodejs, npm, bzip2 
        state: present

  - name: Unziping software-I
    command: "cd /root/"

  - name: Unzipping Software-II
    command: tar -xvjf abhikeliye_nodecode.tar

  - name: Installing package.json LIBRARIES.
    npm:
        path: /root 

  - name: Instaling pm2 latest.
    npm:
        name: pm2
        state: latest 
        global: yes

  - name: CREATING SYSTEM DEAMON FOR NODE APPLICATION
    command: pm2 start /root/start.js

# -----------------------------------------------------------------------------
# part-I of nodejs app finished. 
# remaining tasks :-
# 1. Pull code from git directly.
# 2. research more for security.
# 3. research to replace 'command' module.
# ------------------------------------------------------------------------------


- name: CREATING A REVERSE-PROXY WEB-SERVER.
  hosts: nginx2
  tasks:
  - name: Instaling epel-release.
    yum:
        name: "epel-release"
        state: present

  - name: Installing NGINX BIATCH.
    yum:
        name: nginx
        state: present

#															// Risky buisness: Remeber to change IP in conf file, for both app and web.
  - name: CONFIGURING NGINX BIAAATCH...
    copy:
           src: "/home/samurai/code/ansible/nginx.conf"
           dest: "/etc/nginx/nginx.conf"
           owner: root
           group: root

  - name: INITIATING WEB_SERVER BIAAAAATCH.......
    command: "nginx -c /etc/nginx/nginx.conf"
























